### ISSUE TITLE
OSError: filename.cdf is not a CDF file or a non-supported CDF!

### ISSUE THREAD

**Issue by willekemulder** [MAVENSDC/cdflib#121]
This is my introduction to CDF files, but have no idea what non-supported means, and how I could open it

**Comment by dstansby** [comment]
Can you provide a link to the CDF file that's giving you this error? cdflib checks for a magic number at the start of a file to see if it's supported, but perhaps we're doing this wrong somehow.

**Comment by Anita-Mohebbi** [comment]
I have the same issue. Would you tell me what shall I do?

**Comment by candeynasa** [comment]
There are multiple other file formats that sometimes carry an extension of "cdf", and other libraries are required to read them. In particular, netCDF files might have a "cdf" extension instead of the more common ".nc".

**Comment by Anita-Mohebbi** [comment]
Thank you!
I looked at the folder where I downloaded my files and found out some had not been downloaded completely. So, by deleting them and re-downloading the problem is solved.
