### ISSUE TITLE
cdflib does not raise an error or a warning when the file does not exist

### ISSUE THREAD

**Issue by bevoorrading** [MAVENSDC/cdflib#153]
Hello,

When I try to read a CDF-file with cdflib but the path or filename is incorrect, cdflib does not raise an error or a warning. It only creates an empty CDF object without any variables.

I don't know if this is intended behaviour, but it doesn't seem desirable. This may cause confusing problems further down the line if people don't realize the file or path was wrong. Possibly another issue (#100) may have been caused by this.

It seems preferable to me if cdflib would raise an error or at least a warning in this case.

**Comment by dstansby** [comment]
Yes, this should definitely raise an error
