### ISSUE TITLE
`varinq` returns `Pad` as numpy array and does not have `to_np=False` option like `varattsget`

### ISSUE THREAD

**Issue by rweigel** [MAVENSDC/cdflib#176]
Using cdflib `0.4.4` and Python 3.9, I noticed this inconsistency when trying to dump CDF metadata as JSON.

The attached CDF file was created by the CDAWeb REST server.

```
cdffile = cdflib.CDF('tha_l2s_efi_20230321000001_20230321000009.cdf')
cdfinfo  = cdffile.cdf_info()
variables = [*cdfinfo['rVariables'], *cdfinfo['zVariables']]
cdfVarInfo = cdffile.varinq(variable=variables[0])
print(cdfVarInfo)
```
[tha_l2s_efi_20230321000001_20230321000009.cdf.gz](https://github.com/MAVENSDC/cdflib/files/11457600/tha_l2s_efi_20230321000001_20230321000009.cdf.gz)

**Comment by dstansby** [comment]
In version 1.0.0 I've removed the `to_np` arguments, and `cdflib` returns arrays everywhere now - if you need a list, then the array can be manually converted to a list after it's returned by cdflib.
