### ISSUE TITLE
cdfepoch.to_datetime is returning values with no timezone

### ISSUE THREAD

**Issue by berniegsfc** [MAVENSDC/cdflib#224]
The datetime values returned by cdfepoch.to_datetime() have no timezone value set.  It should be set to timezone.utc.

**Comment by dstansby** [comment]
👍 - would you be able to contribute a pull request with that change/fix?

**Comment by berniegsfc** [comment]
I haven't looked at the source code but I expect it to be an easy fix.  But I won't have time to do anything until at least next week.  If I have time, I'll look at it next week.
