### ISSUE TITLE
unixtime doesn't was for a single epoch

### ISSUE THREAD

**Issue by grenoya** [MAVENSDC/cdflib#25]
When trying to convert a single epoch value and ended up with the following error (please look below my message). My "dt0" variable is a numpy.ndarray of shape (1,) (I extracted only 1 record with varget).

cdflib Version: 0.3.5 (problem still exists with curent state of the code)

I haven't found yet a pretty solution to propose as a PR...

****
In [6]: cdfepoch.unixtime(dt0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-5c5160b13458> in <module>()
----> 1 cdfepoch.unixtime(dt0)

~/anaconda3/lib/python3.6/site-packages/cdflib/epochs.py in unixtime(cdf_time, to_np)
    356         for t in time_list:
    357             date = ['year', 'month', 'day', 'hour', 'minute', 'second', 'microsecond']
--> 358             for i in range(0,len(t)):
    359                 if i > 7:
    360                     continue

TypeError: object of type 'numpy.int64' has no len()
******

**Comment by bryan-harter** [comment]
Thanks for catching that, it should be fixed now.  Sorry for the long delay on this!
