### ISSUE TITLE
Readme doc

### ISSUE THREAD

**Issue by aredshaw** [MAVENSDC/cdflib#28]
Could I contribute some documentation for this project? I am trying to install it and get it working on Windows 10 and am running into issues not mentioned in your Readme doc. I might also contribute other documentation if you are open to that.

My question now is, how do I do this?
> cdf_file = cdflib.CDF('/path/to/cdf_file.cdf')

It is in the documentation that way, but it cannot be a command line prompt, can it? Is this something that needs to be changed in a file somewhere?

**Comment by bryan-harter** [comment]
Sure!  You can clone the repository, make a new branch, and edit the README file. When you are done, you can create a pull request.  You should see a a different tab on this web page for creating pull requests.  

As for the line:

cdf_file = cdflib.CDF('/path/to/cdf_file.cdf')

It should be done inside of a python script, or you could start up python from the command line by typing "python" or "ipython".  Then you have a command line like environment, but all commands must be in python.

**Comment by dstansby** [comment]
Looks like this is fixed, feel free to comment or open another issue if you have any more problems @aredshaw
