### ISSUE TITLE
Convert print statements to warnings

### ISSUE THREAD

**Issue by dstansby** [MAVENSDC/cdflib#40]
Currently there are a lot of places (e.g. when a variable can't be found) that just contain plain `print` statements. These should all be upgraded to at least proper `warnings`, and in some cases I suspect exceptions that halt the program.

**Comment by scivision** [comment]
Would you consider `logging.warning` or similar? This can trivially be configured to simultaneously log which line generated the error and other parameters. It is also easy for the user to set their desired warning verbosity

**Comment by dstansby** [comment]
Definitely think `logging.warning` is the way to go in the long run 👍
