### ISSUE TITLE
enforce gzip 

### ISSUE THREAD

**Issue by jarau-de** [MAVENSDC/cdflib#66]
For my project I need enforce compression on variable level also if the compressed size is  not smaller than uncompressed. This fix is really urgent.

**Comment by bryan-harter** [comment]
The official CDF library also does not allow compression of the variable if the compressed size is larger than the uncompressed size.  To my knowledge there is no way to enforce it in any of the other language implementations (C, IDL, etc) of the CDF library.  So my inclination is to not allow it in this python version, because that would mean that this library could create CDF files that the primary library would never create.  

Is there an issue that occurs when reading a variable that is not compressed?  If so, we could work on fixing that.  

In the meantime, you can try increasing the blocking size parameter, that could increase the chances of the variable compression kicking in.

**Comment by jarau-de** [comment]
Good to know, but if I use Matlab with the low level cdflib interface the cdfxp tool shows the following:
(first line Matlab2018a, second Python3)
Variables: 0r/1z, Records: 0r/1z, Compression: None, Checksum: None
Variables: 0r/1z, Records: 0r/1z, Compression: None, Checksum: None
Item/Variable         DataSpec  Dimensionality              Variances   Output
"Flags_B"             UINT4/1   0:[]                        T/          YES
"Flags_B"             UINT4/1   0:[]                        T/          YES
Item/Variable         Sparseness          Compression         Reserve Blocking
"Flags_B"             None                GZIP.9              0       16384
"Flags_B"             None                None                n/a     1

I putted in the value '1', so there shouldn't be any compression.
Maybe that there is no compression effectively but the compression flag (GZIP.9) will be always set with the original native cdflib.  I think that's a bug with the Python cdflib. The variable should be declared compressed despite of the internal behaviour. Please correct that. I'm really in a hurry. Need to finish my code this week.

**Comment by bryan-harter** [comment]
Ah ok sorry about that, the flag for compression was never set.  It should be fixed now, let me know if that works.

**Comment by jarau-de** [comment]
Thanks a lot for your fast support. You saved me. There is only one minor issue. The blocking factor differs from the Matlab version (1 vs. 16384). Is that to be expected?

**Comment by bryan-harter** [comment]
Its possible that there is a bug there with how the block size is labelled in the variable description, but I'd need to compare it to the CDF library to make sure.  For the time being, it shouldn't affect how the variable is read back out of the CDF file.

**Comment by jarau-de** [comment]
The GZIP flag is set now but something strange happens with the data if I read them with cdfxp. All variable which were really zipped seem to be ok. For all other they are shifted up. That means if I have three records with a = 1,1,1, b=2,2,2 and c=3,3,3 following happens:
rec0: a = 1, b = 2, c = 3
rec1: a = 2, b = 3, c = 3
rec2: a = 3, b = 3, c = ?
This is only for demonstration purpose. I'm using double values. But somehow value from one variable are apear in the previous variable in the next record. With the former version of Python cdflib everything was good.

**Comment by jarau-de** [comment]
Any progress? In the meantime I had to use my own cdflib interface. But it would be nice to hear from you.

**Comment by bryan-harter** [comment]
Hi there, sorry for the delay.  I'm having trouble getting your error, is there any code that your can provide that replicates the issue?  I tried reading and writing multidimensional variables a few different ways, but they all seem to behave normally for me.  

As for documentation from the CDF library, here you go: 

https://spdf.gsfc.nasa.gov/pub/software/cdf/doc/cdf371/cdf371ug.pdf

at the bottom of page 14 is a footnote:  " If compressed data turns out to be larger than uncompressed data, it makes no sense to use compression, thus variable
data will be stored in a CDF uncompressed, even if a compression is set"

**Comment by jarau-de** [comment]
Yes you are right. But obviously (compared with original cdflib) the variable is also flagged as compressed if not compressed internally. But there is one bit difference to your approach: the blocking factor. In cdf360ug.pdf page 46 is discribed for standard variables that :
"The variable's blocking factor specifies the minimum number of records to allocate when
an application writes to an unallocated record."
Your approach sets the blocking factor for such "compressed uncompressed variables" to 1. That means that only one record will be allocated nonetheless the record length. That's obviously wrong at least if you are using the cdfxp for inspecting the cdf file. I've set the blocking factor for such variables manually to the length of the records and everything seems work properly. If you increase the blocking factor by one you can see that the following two records of the next variable are now shown in the right way and wrong from the third record. I also observed different blocking factors for compressed variables in your cdflib and the standard cdflib. It would be nice to have a full equivalent behaviour.
Here comes a short Python 3.6 example:

`import cdflib
from numpy import *

cdf = cdflib.cdfwrite.CDF(cdfName, delete=True)
var_spec = {
    'Variable':     'test',
    'Data_Type':    cdf.CDF_DOUBLE,
    'Num_Elements': 1,
    'Rec_Vary':     cdf.VARY,
    'Dim_Sizes':    [],
}

dat = random.rand(60)
cdf.write_var(var_spec, var_data=dat)

var_spec = {
    'Variable':     'test2',
    'Data_Type':    cdf.CDF_DOUBLE,
    'Num_Elements': 1,
    'Rec_Vary':     cdf.VARY,
    'Dim_Sizes':    [],
}

dat = random.rand(60)
cdf.write_var(var_spec, var_data=dat)

cdf.close()
`

**Comment by bryan-harter** [comment]
I had forgotten to mention this , but a few days prior to your comment I had released a new version that fixed the blocking factor issue.  So if a variable is set to compressed, then the blocking factor should always be shown correctly.  It was actually only an issue with how the blocking factor was labelled, and not how it was actually stored.  

With the new version do you still get the same error with the values being overwritten?

**Comment by bryan-harter** [comment]
Since this is a different issue than the one initially stated in the title I'm going to close this, but feel free  to open another issue if the problem persists
