### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by tron22** [MAVENSDC/cdflib#76]
I have a basic python tuple list of [(Datetime, Float)]. I'm just looking to simply output this to a cdf. I've followed the directions and performed the pip install cdflib. I've also git pulled this repo and tried to follow the sample use. Anyone have any suggestions to help?

**Sample use "Use a master CDF file as your template"**
    - I don't have any CDF file. I'm trying to write one. If a master file is recommended, is one not provided?
    - What is happening with the indentation on the first 'if'... Currently neither of the lines following the 1st 'if' are indented and are therefore not inside of it... If this is on purpose what is the purpose of the first 'if'. If they are both meant to be indented then cdf_file.file in the 2nd 'if' is not initialized unless the 1st 'if' is True. 
    - What is the file /path/to/swea_file.cdf in cdf_file=cdfwrite.CDF('/path/to/swea_file.cdf',cdf_spec=info,delete=True)

**cdfwrite.py - "Creates an empty CDF file."**
 - I run cdfwrite.py and get "Process finished with exit code 0." No new file.

**Comment by vsoch** [comment]
Did you try using some of the code from the tests to start? For example, this file https://github.com/MAVENSDC/cdflib/blob/master/tests/test_cdfwrite.py with Python 3.7 I wrote a file by doing:

```python
import numpy as np
from cdflib import cdfwrite
from cdflib import cdfread
import pytest
from pathlib import Path

def cdf_create(fn: Path, spec: dict):
    # str(fn) is a Python==3.5 workaround
    return cdfwrite.CDF(str(fn), cdf_spec=spec)

fn = 'test.cdf'
tfile = cdf_create(fn, {'Checksum': True})
var_spec = {}
var_spec['Variable'] = 'Variable1'
var_spec['Data_Type'] = 4
var_spec['Num_Elements'] = 1
var_spec['Rec_Vary'] = True
var_spec['Dim_Sizes'] = []
varatts = {}
varatts['Attribute1'] = 1
varatts['Attribute2'] = '500'

tfile.write_var(var_spec, var_attrs=varatts,
                var_data=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
tfile.close()
```
seems like a good start!

**Comment by dstansby** [comment]
Looks like this is solved. If not leave a comment and I can re-open!
