### ISSUE TITLE
Adding package to conda forge

### ISSUE THREAD

**Issue by AlexS12** [MAVENSDC/cdflib#80]
Hi! Just wanted to let you know that I am trying to include a recipe in conda-forge for this package. 

https://github.com/conda-forge/staged-recipes/pull/10847

In case any of you wants to be listed as a mantainer, just let me know!

**Comment by dstansby** [comment]
Brilliant, thanks a lot for this! I'm happy to be listed as a maintainer.

**Comment by AlexS12** [comment]
:+1: Added!
