### ISSUE TITLE
f-string breaking Python 3.5 compatibility

### ISSUE THREAD

**Issue by smithara** [MAVENSDC/cdflib#87]
There's (at least one) f-string at https://github.com/MAVENSDC/cdflib/blob/1d58d7219a8d4d9a709472ccef7ff7f1eb33860d/cdflib/cdfread.py#L510 - the feature was only introduced in Python 3.6 so it breaks under 3.5

Rather than fixing, I wonder if 3.5 support could be dropped? Since I'm sure we all love f-strings! and [Numpy dev have already dropped 3.5](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table).

I guess it could be a contentious issue for the less-actively maintained scientific libraries and systems, though my impression is that this is generally improving across communities. Should libraries like this one adopt some common deprecation policy from elsewhere? Maybe from PyHC, sunpy, astropy...?

**Comment by hugovk** [comment]
I think it's safe to drop Python 3.5: it goes end-of-life next month on 2020-09-13.

* https://devguide.python.org/#status-of-python-branches

NumPy and other Scientific Python projects (such as Matplotlib, scikit-learn, IPython, Jupyter, yt, SciPy and scikit-image) have adopted a community policy for the minimum Python and NumPy versions a project needs to support.

The idea is to take the pressure off projects feeling they need to support all non-EOL versions. It currently suggests that even 3.6 could be dropped if the project wishes (although it's not mandatory). Anyway, dropping 3.5 should be fine.

* https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by dstansby** [comment]
I'm 👍 for dropping python 3.5 support; would be good to get @bryan-harter's input before making the final decision.

**Comment by bryan-harter** [comment]
Yep I'm good with dropping 3.5

**Comment by hugovk** [comment]
Please see PR #91.
