### ISSUE TITLE
write_var():  Data_Type:   CDF_CHAR , error

### ISSUE THREAD

**Issue by Henry-MaL** [MAVENSDC/cdflib#90]
cdf_file.write_var(var_info, var_attrs=var_attrs, var_data=var_data)

var_data:  {'Rec_Ndim': 1, 'Rec_Shape': [3], 'Num_Records': 1, 'Records_Returned': 0, 'Item_Size': 20, 'Data_Type': 'CDF_CHAR', 'Data': array([[['O2+ FlowV X DQ (STA)'],
        ['O2+ FlowV Y DQ (STA)'],
        ['O2+ FlowV Z DQ (STA)']]], dtype='<U20')}

error: unpack requires a buffer of 60 bytes

**Comment by dstansby** [comment]
Could you post a full and self contained code listing so the error can be reproduced?

**Comment by Henry-MaL** [comment]
> 您能否发布完整且自包含的代码清单，以便可以重现该错误？

# read
cdf_master = cdfread.CDF('mvn_insitu_kp-4sec_20150308_v15_r05.cdf')
print(cdf_master.file)

if cdf_master.file:
    # Get the cdf`s specification
    info = cdf_master.cdf_info()
    cdf_file = cdfwrite.CDF('new_mvn_cdf.cdf', cdf_spec=info, delete=True)
    # print(dir(cdf_file))
    # print(cdf_file.path)
    # todo bug   : not file attr
    # if not cdf_file.file:
    #     cdf_master.close()
    #     raise OSError('Problem writing file... Stop')

    # Get the global attributes
    global_attrs = cdf_master.globalattsget(expand=True)
    # Write the global attributes
    cdf_file.write_globalattrs(global_attrs)

    zVars = info['zVariables']
    # Loop thru all the zVariables
    for x in range(0, len(zVars)):
        # Get the variable`s specification
        var_info = cdf_master.varinq(zVars[x])
        print('Z=====>', x, ':', var_info['Variable'])

        # Get the variables`s attributes
        var_attrs = cdf_master.varattsget(zVars[x], expand=True)

        if var_info['Sparse'].lower() == 'no_sparse':
            # print(var_info['Sparse'])
            # A variable with no sparse records... get the variable data
            var_data = cdf_master.varget(zVars[x], expand=True)
            # Create the zVariable, write out the attributes and data
            print('data: ', var_data)
            # todo : Data_type: CDF_Char    do not write
            # try:
            cdf_file.write_var(var_info, var_attrs=var_attrs, var_data=var_data)
            # except Exception as e:
            #     print(var_info)
            #     print(var_attrs)
            #     print(var_data)
            #     print(e)

        else:
            # A variable with sparse records...
            # data is in this form [physical_record_numbers, data_values]
            # physical_record_numbers (0-based) contains the real record
            # numbers. For example, a variable has only 3 physical records
            # at [0, 5, 10]:
            var_recs = [0, 5, 10]
            # data_values could contain only the physical records' data or
            # both the physical and virtual records' data.
            # For example, a float variable of 1-D with 3 elements with only
            # 3 physical records at [0,5,10]:
            var_data = [[5.55000000e+01, -1.00000002e+30, 6.65999985e+01],
                       [6.66659973e+02, 7.77770020e+02, 8.88880005e+02],
                       [2.00500000e+02, 2.10600006e+02, 2.20699997e+02]]
            # Or, with virtual record data embedded in the data:
            # vardata = [[  5.55000000e+01, -1.00000002e+30,  6.65999985e+01],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [  6.66659973e+02,  7.77770020e+02,  8.88880005e+02],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [ -1.00000002e+30, -1.00000002e+30, -1.00000002e+30],
            #            [  2.00500000e+02,  2.10600006e+02,  2.20699997e+02]]
            # Records 1, 2, 3, 4, 6, 7, 8, 9 are all virtual records with pad
            # data (variable defined with 'pad_sparse').
            print('x'*50)
            var_data = np.asarray(var_data)
            # Create the zVariable, and optionally write out the attributes
            # and data
            cdf_file.write_var(var_info, var_attrs=var_attrs, var_data=[var_recs, var_data])

        rVars = info['rVariables']
        # print('no of rvars=',len(rVars))
        # Loop thru all the rVariables
        for x in range (0, len(rVars)):
            varinfo=cdf_master.varinq(rVars[x])
            print('R =============>', x, ': ', varinfo['Variable'])
            var_attrs=cdf_master.varattsget(rVars[x], expand=True)
            if varinfo['Sparse'].lower() == 'no_sparse':
                var_data = [[5.55000000e+01, -1.00000002e+30, 6.65999985e+01],
                                   [6.66659973e+02, 7.77770020e+02, 8.88880005e+02],
                                   [2.00500000e+02, 2.10600006e+02, 2.20699997e+02]]
                # Create the rVariable, write out the attributes and data
                cdf_file.write_var(varinfo, var_attrs=var_attrs, var_data=var_data)
            else:
                var_recs = [0, 5, 10]
                var_data = [[5.55000000e+01, -1.00000002e+30, 6.65999985e+01],
                            [6.66659973e+02, 7.77770020e+02, 8.88880005e+02],
                            [2.00500000e+02, 2.10600006e+02, 2.20699997e+02]]
                var_data = np.asarray(var_data)
                cdf_file.write_var(varinfo, var_attrs=var_attrs,
                           var_data=[var_recs, var_data])

    cdf_master.close()
    cdf_file.close()

**Comment by bryan-harter** [comment]
Seems like the error occurs because in the function _convert_nptype in the cdfwrite module, there is no option to convert string data to bytes.  I think there would need to be a another like for `elif ((data_type) == 51) or ((data_type)==52):` to handle converting strings to a list of bytes.

**Comment by bryan-harter** [comment]
Here was the file I was trying with by the way, I assume it came from CDAWeb:

[mvn_insitus_kp-4sec_20150308000000_20150310000000.zip](https://github.com/MAVENSDC/cdflib/files/5086806/mvn_insitus_kp-4sec_20150308000000_20150310000000.zip)

**Comment by Henry-MaL** [comment]
> Seems like the error occurs because in the function _convert_nptype in the cdfwrite module, there is no option to convert string data to bytes. I think there would need to be a another line for `elif ((data_type) == 51) or ((data_type)==52):` to handle converting strings to a list of bytes.

I already tried that, but have the same error.

**Comment by bryan-harter** [comment]
It looks like that aside from that error, the other issue was that for some reason there was a bunch of null characters in the string.  So I just pushed up a change that will strip away the null characters, and then encode the remaining string as bytes.  With the latest master push, it looks like the sample code above works.
