### ISSUE TITLE
test_compute_cdftt2000 failure

### ISSUE THREAD

**Issue by dstansby** [MAVENSDC/cdflib#92]
The following hypothesis example is failing:

```python
=================================== FAILURES ===================================

____________________________ test_compute_cdftt2000 ____________________________

>   ???

tests/test_epochs.py:166: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dtime = datetime.datetime(2292, 5, 1, 0, 0)

    @given(random_dtime)

    @settings(max_examples=100)

    @example(datetime(1972, 1, 1, 0, 0))

    def test_compute_cdftt2000(dtime):

        random_time = [dtime.year, dtime.month, dtime.day,

                       dtime.hour, dtime.minute, dtime.second,

                       dtime.microsecond // 1000,  # Millisecond

                       randint(0, 999),     # Microsecond

                       randint(0, 999),     # Nanosecond

                       ]

        x = cdfepoch.breakdown(cdfepoch.compute(random_time))

        for i, t in enumerate(x):

>           assert t == random_time[i], f'Time {random_time} was not equal to {x}'

E           AssertionError: Time [2292, 5, 1, 0, 0, 0, 0, 864, 394] was not equal to [1707, 10, 12, 0, 26, 3, 291, 312, 778]

E           assert 1707 == 2292

E             +1707

E             -2292

tests/test_epochs.py:177: AssertionError
```

**Comment by thomas-nilsson-irfu** [comment]
`dtime = datetime.datetime(2292, 5, 1, 0, 0)` is outside of valid range for CDF TT2000.

As stated on https://cdf.gsfc.nasa.gov/html/leapseconds_requirements.html:
> 2.1 CDF Internals
> The recommended FILLVAL is -9223372036854775808LL (hex '8000000000000000'XLL), which is more conveniently entered as 9999-12-31T23:59:59.999999999. Although primarily used internally to the CDF library, the PADVALUE is set to -9223372036854775807LL, which is more conveniently entered as 0000-01-01T00:00:00.000000000. Valid values range from 1707-09-22T12:13:15.145224194 to 2292-04-11T11:46:08.670775807.

Note: the text on this webpage appears to be written before the last three added leap second (and not updated since) meaning the actual range now ends on `2292-04-11T11:46:05.670775807`.

**Comment by dstansby** [comment]
Ah great, that means we just need to adjust the range of dates that are being generated for this test then.
