### ISSUE TITLE
Release 0.3.19 not available on PyPI

### ISSUE THREAD

**Issue by johan12345** [MAVENSDC/cdflib#94]
It seems that the latest release [0.3.19](https://github.com/MAVENSDC/cdflib/releases/tag/0.3.19) was not yet uploaded to [PyPI](https://pypi.org/project/cdflib/#history). Was that intentional?

**Comment by dstansby** [comment]
Nope, it should be there. I thought @bryan-harter had set it up to auto-upload when the release is tagged, but that doesn't seem to be working. I'll do a manual upload later today, thanks for reporting!

**Comment by johan12345** [comment]
Thanks!

**Comment by bryan-harter** [comment]
The setup.cfg file also needs to be updated to a new version number when you tag a new version.  So it looks like it ran, but it attempted to build/push the package as 0.3.18 again.  So I just changed the version number in the setup file and tagged the commit again.  

I did actually find another bug with the deployment script which I just fixed, so 0.3.19 should be pushed now.

**Comment by bryan-harter** [comment]
And also, meta.yaml will need to be updated with the new version number as well to get a new anaconda version.  I just did that, so 0.3.19 should be on anaconda now as well.

**Comment by johan12345** [comment]
Yes, It's now available on PyPI. Thanks!
