### ISSUE TITLE
Tempfiles generated while decompressing are not properly deleted

### ISSUE THREAD

**Issue by kieran-lemayai** [MAVENSDC/cdflib#95]
I was running some operations against a massive amount of CDF files and suddenly ran out of disk space. When I checked `/tmp`, I noticed that it was full of `.cdf` files, even after cleaning out everything in my session and running the GC.

I'm guessing the issue happens here: https://github.com/MAVENSDC/cdflib/blob/master/cdflib/cdfread.py#L723

`tempfile` files are supposed to delete the underlying file once they go out of scope and get destroyed. Technically the `NamedTemporaryFile` object goes out of scope once this function exits. However, I'm guessing that since the `Path` object has some kind of handle on the file, it can't delete the underlying file, which makes sense since otherwise none of the code would work. So the file just sits there even after the `CDF` object gets deleted, at least until system restart, when `/tmp` gets cleared. (No idea how this acts on Windows.)

Environment: Python 3.6, library release 0.3.19, RHEL 8.2

**Comment by dstansby** [comment]
Yep, I've just run across this...
