### ISSUE TITLE
epochs.py in cdflib is using the local time zone instead of UTC

### ISSUE THREAD

**Issue by supervised** [MAVENSDC/cdflib#96]
Copying a bug report from X. N. Chu  (@xnchu), reported to pySPEDAS (with a minor correction to the expected result):

> The epoch is converted to unix_time at line 195 in cdf_to_tplot.py
> If cdflib is used, it is converted using function unixtime at line 192 in epochs.py.
> The problem is line 222:
> unixtime.append(datetime.datetime(*date).timestamp())
> It assumes local time instead of UTC. Therefore, the time is offset by your local time.
> The codes to reproduce the error is attached below.
> The result should be 2010-01-01/00:00:00.

```
import pyspedas
import numpy as np
import pandas as pd
trange=['2010-01-01/00:00:00', '2010-01-02/00:00:00']
varname = 'BX_GSE'
data_omni = pyspedas.omni.data(trange=['2010-01-01/00:00:00', '2010-01-02/00:00:00'],notplot=True,varformat=varname,time_clip=True)
data = np.array(data_omni[varname]['y'])
unix_time = np.array(data_omni[varname]['x'])
date_time = pd.to_datetime(data_omni[varname]['x'],unit='s')
print(date_time[0])
```

I was able to reproduce the problem without astropy installed (if astropy is installed, pytplot doesn't use epochs.py)

**Comment by dstansby** [comment]
Thanks for reporting! Is it possible to modify the example to reproduce the same bug without `pyspedas`?

**Comment by supervised** [comment]
Sure - I used the following file:
https://spdf.gsfc.nasa.gov/pub/data/omni/omni_cdaweb/hro_1min/2010/omni_hro_1min_20100101_v01.cdf

and just checked the first time in the Epoch variable:

```
>>> import cdflib
>>> cdf_file = cdflib.CDF('/Users/eric/omni_hro_1min_20100101_v01.cdf')
>>> epoch = cdf_file.varget('Epoch')
>>> unixtime = cdflib.cdfepoch.unixtime(epoch[0])
>>> unixtime
[1262332800.0]
```

which is: 2010-01-01/08:00 (I'm in the Pacific time zone)

I loaded the same file with IDL SPEDAS and Autoplot and the first element of Epoch is supposed to be: 

1262304000.0

which is: 2010-01-01/00:00

**Comment by dstansby** [comment]
Okay, I think we broke this with https://github.com/MAVENSDC/cdflib/pull/84, sorry! I've opened https://github.com/MAVENSDC/cdflib/pull/97 which should fix the issue.

**Comment by supervised** [comment]
Thanks!
